import { Button, VerticalBox, LineEdit } from "std-widgets.slint";


export component AppWindow inherits Window {
    in-out property <string> input;
    in property <image> picture_source <=> picture.source;
    height: 900px;
    width: 1200px;
    title: "Face recognition";
    background: grey;
    callback click();
    callback camera();
    callback input_changed(string);
    VerticalBox {
        y: 80px;
        height: 10%;
        width: parent.width / 2;
        Text {
            text: "Welcome to the face recognition application interface";
            
        }
	input := LineEdit {
	font-size: 14px;
	width: parent.width;
	height: 20px;
	placeholder-text: "Enter a file path";
    edited => {input_changed(input.text);}
	}
        Button {
            text: "Load file";
            clicked => {
		root.click();
            }
        }
        Button {
            text: "Enable camera";
            clicked => {
		root.camera();
            }
        }
        picture_rect := Rectangle {
            
            picture:=Image { }
        }
    }
    
    
}
