[package]
name = "projet_s4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
process_path = "0.1.3"
image="0.23.14"
ndarray="*"
ndarray-stats="*"
